
spring:
  application:
    name: gateway
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      routes:
        - id: microservice
          uri: lb://MICROSERVICE
          predicates:
            - Path=/**
server:
  port: 8080